version: '2'
services:
  Apollo-app:
    image: Apollo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - APOLLO_DB_HOST=localhost
      - APOLLO_DB_PORT=3306
      - APOLLO_DB_SCHEMA=sallefy
      - APOLLO_DB_USER=user
      - APOLLO_DB_PASSWORD=password
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  Apollo-mysql:
    extends:
      file: mysql.yml
      service: Apollo-mysql
